### ISSUE TITLE
Satosa gives error 500 instead of 404

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SCZ-deploy#23]
When a non-existing file is requested from satosa (for example `https://proxy.scz-vm.net/md/bla.xml`), satosa returns a 500 error instead of a 404.  It seems it doesn't check if the file exists before trying some kind of substitution operation:

```
jan 17 10:04:32 proxy satosa[11626]: [2018-01-17 10:04:32] [INFO ]: CUSTOM_ALIAS_SERVICE: _handle: md - frontend.xml - /opt/satosa/satosa-env/metadata/frontend.xml
jan 17 10:04:32 proxy satosa[11626]: [2018-01-17 10:04:32] [ERROR]: [urn:uuid:efc45796-d6d7-49a4-843c-71e97485b533] Uncaught exception
jan 17 10:04:32 proxy satosa[11626]: Traceback (most recent call last):
jan 17 10:04:32 proxy satosa[11626]:   File "/opt/satosa/satosa-env/lib/python3.5/site-packages/satosa/base.py", line 268, in run
jan 17 10:04:32 proxy satosa[11626]:     resp = self._run_bound_endpoint(context, spec)
jan 17 10:04:32 proxy satosa[11626]:   File "/opt/satosa/satosa-env/lib/python3.5/site-packages/satosa/base.py", line 216, in _run_bound_endpoint
jan 17 10:04:32 proxy satosa[11626]:     return spec(context)
jan 17 10:04:32 proxy satosa[11626]:   File "/opt/satosa/satosa-env/lib/python3.5/site-packages/satosa/micro_services/custom_alias.py", line 44, in _handle
jan 17 10:04:32 proxy satosa[11626]:     for search, replace in context.state['substitutions'].items():
jan 17 10:04:32 proxy satosa[11626]:   File "/opt/satosa/satosa-env/lib/python3.5/site-packages/satosa/state.py", line 220, in __getitem__
jan 17 10:04:32 proxy satosa[11626]:     return self._state_dict[key]
jan 17 10:04:32 proxy satosa[11626]: KeyError: 'substitutions'
jan 17 10:04:32 proxy satosa[11626]: [2018-01-17 10:04:32] [ERROR]: Unknown error
jan 17 10:04:32 proxy satosa[11626]: Traceback (most recent call last):
jan 17 10:04:32 proxy satosa[11626]:   File "/opt/satosa/satosa-env/lib/python3.5/site-packages/satosa/base.py", line 268, in run
jan 17 10:04:32 proxy satosa[11626]:     resp = self._run_bound_endpoint(context, spec)
jan 17 10:04:32 proxy satosa[11626]:   File "/opt/satosa/satosa-env/lib/python3.5/site-packages/satosa/base.py", line 216, in _run_bound_endpoint
jan 17 10:04:32 proxy satosa[11626]:     return spec(context)
jan 17 10:04:32 proxy satosa[11626]:   File "/opt/satosa/satosa-env/lib/python3.5/site-packages/satosa/micro_services/custom_alias.py", line 44, in _handle
jan 17 10:04:32 proxy satosa[11626]:     for search, replace in context.state['substitutions'].items():
jan 17 10:04:32 proxy satosa[11626]:   File "/opt/satosa/satosa-env/lib/python3.5/site-packages/satosa/state.py", line 220, in __getitem__
jan 17 10:04:32 proxy satosa[11626]:     return self._state_dict[key]
jan 17 10:04:32 proxy satosa[11626]: KeyError: 'substitutions'
jan 17 10:04:32 proxy satosa[11626]: The above exception was the direct cause of the following exception:
jan 17 10:04:32 proxy satosa[11626]: Traceback (most recent call last):
jan 17 10:04:32 proxy satosa[11626]:   File "/opt/satosa/satosa-env/lib/python3.5/site-packages/satosa/proxy_server.py", line 113, in __call__
jan 17 10:04:32 proxy satosa[11626]:     resp = self.run(context)
jan 17 10:04:32 proxy satosa[11626]:   File "/opt/satosa/satosa-env/lib/python3.5/site-packages/satosa/base.py", line 284, in run
jan 17 10:04:32 proxy satosa[11626]:     raise SATOSAUnknownError("Unknown error") from err
jan 17 10:04:32 proxy satosa[11626]: satosa.exception.SATOSAUnknownError: Unknown error
```

**Comment by baszoetekouw** [comment]
Sorry, this seems unrelated.  The exception above is thrown even if the target file exists,

**Comment by baszoetekouw** [comment]
Should be fixed by https://github.com/SURFscz/SATOSA/commit/e408d68edb44510b02c5c5cc7c9df3f795add26a

@mrvanes could you do a sanity check?

**Comment by mrvanes** [comment]
Ik wou zeggen dat de context.state['substitutions'] veilig vervangen zou kunnen worden door een .get('substitutions') maar dat levert een None op en die heeft geen .items(), dus ja... dit lijkt de beste oplossing.
