### ISSUE TITLE
metadata generation should fail gracefully if pyff isn't running

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SCZ-deploy#24]
gen-metadata fails with a rather nasty-looking error if pyff isn't running.  It should be straightforward to fail a bit more gracefully.

```
TASK [satosa : Generate metadata] **********************************************
fatal: [proxy.vm.scz-vm.net]: FAILED! => {
    "changed": true, 
    "cmd": "./gen_metadata", 
    "delta": "0:00:00.704807", 
    "end": "2018-01-17 13:55:55.124074", 
    "rc": 1, 
    "start": "2018-01-17 13:55:54.419267"
}

STDERR:

Setup frontends: ['SamlIdP', 'SamlMirrorIdP', 'OIDC']
The SAML service provider accepts unsigned SAML Responses and Assertions. This configuration is insecure.
The SAML service provider accepts unsigned SAML Responses and Assertions. This configuration is insecure.
Setup backends: ['SamlSP', 'SamlMirrorSP']
Loaded frontend plugins: ['SamlIdP', 'SamlMirrorIdP', 'OIDC']
Loaded backend plugins: ['SamlSP', 'SamlMirrorSP']
Creating SAML backend 'SamlSP' metadata
Backend SamlSP EntityID https://proxy.scz-vm.net/SamlSP/proxy.xml
Creating SAML backend Mirror metadata for 'SamlMirrorSP' and frontend 'SamlIdP'
Traceback (most recent call last):
  File "/opt/satosa/satosa-env/lib/python3.5/site-packages/saml2/mdstore.py", line 811, in __getitem__
    return self.entity[item]
KeyError: 'https://sp-test.scz-vm.net/saml/module.php/saml/sp/metadata.php/default-sp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/satosa/satosa-env/lib/python3.5/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/opt/satosa/satosa-env/lib/python3.5/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/opt/satosa/satosa-env/lib/python3.5/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/satosa/satosa-env/lib/python3.5/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/opt/satosa/satosa-env/lib/python3.5/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/opt/satosa/satosa-env/lib/python3.5/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/opt/satosa/satosa-env/lib/python3.5/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7ff5c8fbc828>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/satosa/satosa-env/lib/python3.5/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/opt/satosa/satosa-env/lib/python3.5/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/opt/satosa/satosa-env/lib/python3.5/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8081): Max retries exceeded with url: /entities/%7Bsha1%7D9cf868c63facb578874f88ec55eb097ee2bbb2bb (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff5c8fbc828>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/satosa/satosa-env/bin/satosa-saml-metadata", line 11, in <module>
    sys.exit(construct_saml_metadata())
  File "/opt/satosa/satosa-env/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/satosa/satosa-env/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/satosa/satosa-env/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/satosa/satosa-env/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/satosa/satosa-env/lib/python3.5/site-packages/satosa/scripts/satosa_saml_metadata.py", line 105, in construct_saml_metadata
    create_and_write_saml_metadata(proxy_conf, key, cert, dir, valid, split_frontend, split_backend, split_module)
  File "/opt/satosa/satosa-env/lib/python3.5/site-packages/satosa/scripts/satosa_saml_metadata.py", line 64, in create_and_write_saml_metadata
    frontend_entities, backend_entities = create_entity_descriptors(satosa_config)
  File "/opt/satosa/satosa-env/lib/python3.5/site-packages/satosa/metadata_creation/saml_metadata.py", line 148, in create_entity_descriptors
    backend_metadata = _create_backend_metadata(backend_modules, frontend_modules)
  File "/opt/satosa/satosa-env/lib/python3.5/site-packages/satosa/metadata_creation/saml_metadata.py", line 83, in _create_backend_metadata
    meta_desc = frontend.get_metadata_desc()
  File "/opt/satosa/satosa-env/lib/python3.5/site-packages/satosa/frontends/saml2.py", line 519, in get_metadata_desc
    ui_info = self.idp.metadata.extension(entity_id, "spsso_descriptor", "{}&UIInfo".format(UI_NAMESPACE))
  File "/opt/satosa/satosa-env/lib/python3.5/site-packages/saml2/mdstore.py", line 996, in extension
    srvs = _md[entity_id][typ]
  File "/opt/satosa/satosa-env/lib/python3.5/site-packages/saml2/mdstore.py", line 815, in __getitem__
    'Accept': SAML_METADATA_CONTENT_TYPE})
  File "/opt/satosa/satosa-env/lib/python3.5/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/satosa/satosa-env/lib/python3.5/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/satosa/satosa-env/lib/python3.5/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/satosa/satosa-env/lib/python3.5/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/opt/satosa/satosa-env/lib/python3.5/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8081): Max retries exceeded with url: /entities/%7Bsha1%7D9cf868c63facb578874f88ec55eb097ee2bbb2bb (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff5c8fbc828>: Failed to establish a new connection: [Errno 111] Connection refused',))


MSG:

non-zero return code

	to retry, use: --limit @/home/bas/Workspace/Repositories/SCZ-deploy/provision.retry

PLAY RECAP *********************************************************************
```

**Comment by mrvanes** [comment]
Can't reproduce in VM, current deploy.

**Comment by baszoetekouw** [comment]
This is ancient, anyway.  Haven't seen this in any recent builds.
